<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CdliUserProfile\Module'                                => __DIR__ . '/Module.php',
    'CdliUserProfile\Controller\ProfileController'          => __DIR__ . '/src/CdliUserProfile/Controller/ProfileController.php',
    'CdliUserProfile\Service\Profile'                       => __DIR__ . '/src/CdliUserProfile/Service/Profile.php',
    'CdliUserProfile\Integration\AbstractIntegration'       => __DIR__ . '/src/CdliUserProfile/Integration/AbstractIntegration.php',
    'CdliUserProfile\Integration\ZfcUser'                   => __DIR__ . '/src/CdliUserProfile/Integration/ZfcUser.php',
    'CdliUserProfile\Integration\IntegrationInterface'      => __DIR__ . '/src/CdliUserProfile/Integration/IntegrationInterface.php',
    'CdliUserProfile\Options\ModuleOptions'                 => __DIR__ . '/src/CdliUserProfile/Options/ModuleOptions.php',
    'CdliUserProfile\Model\ProfileSection'                  => __DIR__ . '/src/CdliUserProfile/Model/ProfileSection.php',
    'CdliUserProfile\Model\ProfileSectionInterface'         => __DIR__ . '/src/CdliUserProfile/Model/ProfileSectionInterface.php',
    'CdliUserProfile\Validator\NoRecordExistsExceptIgnored' => __DIR__ . '/src/CdliUserProfile/Validator/NoRecordExistsExceptIgnored.php',
    'CdliUserProfile\Form\Section\ZfcUser'                  => __DIR__ . '/src/CdliUserProfile/Form/Section/ZfcUser.php',
    'CdliUserProfile\Form\Section\ZfcUserFilter'            => __DIR__ . '/src/CdliUserProfile/Form/Section/ZfcUserFilter.php',
);
